import Link from 'next/link'
import type { CSSProperties } from 'react'
import type { Locale } from '@/lib/get-locale'
import s from './recognition-page.module.css'
import { RecognitionSection04Final } from './recognition-section04-final'
import { ProcessNode, type ProcessIconName } from './recognition-process-node'
import { RecognitionSectionNote } from './recognition-section-note'

const copy = {
  en: {
    heroEyebrow: 'Vision · Recognition · Workflows', heroTitle: 'Smart Recognition Systems.', heroBody: 'Computer vision systems for wildlife, production quality, agriculture and security that connect detections to real operational workflows.', heroPrimary: 'Book a diagnosis', heroSecondary: 'See use cases',
    heroSignal: ['Intelligence built on real data.', 'Impact delivered in the field.'],
    useEyebrow: '02 · Core Use Cases', useTitle: 'Recognition across real operations.', useIntro: 'One recognition layer. Multiple operational contexts. Each use case connects visual evidence to a measurable workflow.', useGridLabel: 'CORE RECOGNITION AREAS',
    useCases: [['Wildlife Recognition','Detect cougar, pudú and conservation events in forests, parks and remote areas.'],['Cattle Recognition','Count livestock, register feeding events and monitor herd movement.'],['Production Quality Recognition','Measure size, color, defects and premium quality across products and batches.'],['Security Recognition','Detect people, vehicles, intrusion and perimeter events in critical areas.']],
    valueEyebrow:'03 · Value Chain', valueTitle:'Detection becomes action.', valueBody:'N3uralia transforms raw detections into operational workflows that create records, alerts, and business actions across your organization.', valueNoteTitle:"Events don’t become workflows by themselves.", valueNoteBody:'A detection only creates value when it becomes a record, an alert, or an action.',
    flow:[['Detect','Capture events in real time.'],['Identify / Classify','Understand what happened.'],['Evaluate / Score','Assess risk and prioritize.'],['Register / Record','Create a trusted operational record.'],['Trigger Action','Initiate actions across systems.']], trace:'Trace & Improve', traceBody:'Close the loop with visibility and continuous improvement.', valueFooterRight:'Built for operations. Designed for impact.',
    workEyebrow:'Start with one use case.', workTitle:'From diagnosis to pilot to scale.', workBody:'Start with one measurable recognition workflow, prove it in the field, then scale it across teams, sites and systems.', work:[['01','Diagnose','Assess your operation, constraints, and goals.'],['02','Pilot','Deploy a measurable pilot in one site or line.'],['03','Scale','Scale across teams, workflows, and facilities.']], book:'Book a diagnosis', talk:'Talk to us',
  },
  es: {
    heroEyebrow:'Visión · Reconocimiento · Flujos', heroTitle:'Sistemas de reconocimiento inteligente.', heroBody:'Sistemas de visión computacional para fauna, calidad de producción, agricultura y seguridad que conectan detecciones con flujos operacionales reales.', heroPrimary:'Agendar diagnóstico', heroSecondary:'Ver casos de uso', heroSignal:['Inteligencia construida sobre datos reales.','Impacto entregado en terreno.'],
    useEyebrow:'02 · Casos de Uso', useTitle:'Reconocimiento en operaciones reales.', useIntro:'Una capa de reconocimiento. Múltiples contextos operativos. Cada caso conecta evidencia visual con un flujo medible.', useGridLabel:'ÁREAS PRINCIPALES DE RECONOCIMIENTO', useCases:[['Reconocimiento de Fauna','Detecta puma, pudú y eventos de conservación en bosques, parques y zonas remotas.'],['Reconocimiento Ganadero','Cuenta ganado, registra eventos de alimentación y monitorea el movimiento del rebaño.'],['Reconocimiento de Calidad','Mide tamaño, color, defectos y calidad premium en productos y lotes.'],['Reconocimiento de Seguridad','Detecta personas, vehículos, intrusión y eventos perimetrales en áreas críticas.']],
    valueEyebrow:'03 · Cadena de Valor', valueTitle:'La detección se convierte en acción.', valueBody:'N3uralia transforma detecciones en flujos operacionales que crean registros, alertas y acciones de negocio en toda la organización.', valueNoteTitle:'Los eventos no se convierten solos en flujos.', valueNoteBody:'Una detección crea valor cuando se convierte en un registro, una alerta o una acción.', flow:[['Detectar','Captura eventos en tiempo real.'],['Identificar / Clasificar','Comprende qué ocurrió.'],['Evaluar / Puntuar','Evalúa riesgo y prioriza.'],['Registrar','Crea un registro operacional confiable.'],['Activar Acción','Inicia acciones entre sistemas.']], trace:'Trazar y Mejorar', traceBody:'Cierra el ciclo con visibilidad y mejora continua.', valueFooterRight:'Construido para operaciones. Diseñado para impacto.',
    workEyebrow:'Comienza con un caso de uso.', workTitle:'Del diagnóstico al piloto y a escala.', workBody:'Comienza con un flujo de reconocimiento medible, pruébalo en terreno y luego escálalo entre equipos, sitios y sistemas.', work:[['01','Diagnosticar','Evalúa tu operación, restricciones y objetivos.'],['02','Piloto','Implementa un piloto medible en un sitio o línea.'],['03','Escalar','Escala entre equipos, flujos e instalaciones.']], book:'Agendar diagnóstico', talk:'Hablar con nosotros',
  },
} as const

const useCaseAssets=[['/usecase-cougar-clean.webp','Clean dark image of a Chilean cougar for wildlife recognition.'],['/usecase-cow-clean.webp','Clean dark image of a healthy cow for cattle recognition.'],['/usecase-sea-urchin-clean.webp','Sea urchin specimen inspection for production quality recognition.'],['/usecase-security-clean.webp','Human moving through a secured perimeter at night for security recognition.']] as const
const valueIcons: ProcessIconName[] = ['detect','classify','score','record','telegram']

export function RecognitionPage({locale}:{locale:Locale}){const t=copy[locale];return <main className={s.page}>
<section className={`${s.section} ${s.hero}`}><div className={`${s.shell} ${s.heroContent}`}><span className={s.eyebrow}>{t.heroEyebrow}</span><h1>{t.heroTitle}</h1><p className={s.heroBody}>{t.heroBody}</p><div className={s.actions}><Link href={`/${locale}/diagnostico`} className={`${s.button} ${s.buttonPrimary}`}>{t.heroPrimary}</Link><a href="#use-cases" className={s.button}>{t.heroSecondary}</a></div><div className={s.heroSignal} aria-hidden="true"><span className={s.signalMark}/><span>{t.heroSignal[0]}<br/>{t.heroSignal[1]}</span></div></div></section>
<section id="use-cases" className={`${s.section} ${s.useCases}`}><div className={s.shell}><div className={s.useCaseLead}><header className={s.sectionHead}><span className={s.eyebrow}>{t.useEyebrow}</span><h2>{t.useTitle}</h2></header><RecognitionSectionNote icon="contexts">{t.useIntro}</RecognitionSectionNote></div><div className={s.cardGrid} data-label={t.useGridLabel}>{t.useCases.map((item,i)=><article className={s.useCaseCard} key={item[0]}><div className={s.cardMedia}><img src={useCaseAssets[i][0]} alt={useCaseAssets[i][1]} loading="lazy" className={s.visual}/><span className="recognitionMediaCorner recognitionMediaCornerTL" aria-hidden="true"/><span className="recognitionMediaCorner recognitionMediaCornerTR" aria-hidden="true"/><span className="recognitionMediaCorner recognitionMediaCornerBL" aria-hidden="true"/><span className="recognitionMediaCorner recognitionMediaCornerBR" aria-hidden="true"/></div><div className={s.cardBody}><span>0{i+1}</span><h3>{item[0]}</h3><p>{item[1]}</p></div></article>)}</div></div></section>
<section className={`${s.section} ${s.value} valueChainSection`}><div className={s.shell}><div className="valueChainTop"><header><span className={s.eyebrow}>{t.valueEyebrow}</span><h2>{t.valueTitle}</h2><i/></header><RecognitionSectionNote icon="workflow">{t.valueBody}</RecognitionSectionNote></div><div className="valueProcess"><div className="valueProcessMain">{t.flow.map((step,index)=><div className="valueProcessSlot" key={step[0]}><ProcessNode index={`0${index+1}`} icon={valueIcons[index]} title={step[0]} description={step[1]} />{index<t.flow.length-1&&<span className="valueProcessConnector" aria-hidden="true" style={{'--connector-index':index} as CSSProperties}/>}</div>)}</div><div className="valueTrace"><ProcessNode icon="trace" title={t.trace} description={t.traceBody} emphasis /></div></div><footer className="valueFooter"><span aria-hidden="true"/><b>{t.heroSignal[0]}<br/>{t.heroSignal[1]}</b><i/><b>{t.valueFooterRight}</b></footer></div></section>
<RecognitionSection04Final locale={locale}/>
<section className={`${s.section} ${s.work} recognitionSection05`}><div className={s.shell}><figure className="recognitionSection05Figure"><img src="/recognition-section05-diagnosis-pilot-scale.webp" alt={locale==='es'?'N3uralia: del diagnóstico al piloto y a escala, con centro de comando operacional.':'N3uralia: from diagnosis to pilot to scale, with an operational command center.'} loading="lazy"/><div className="recognitionSection05Actions"><Link href={`/${locale}/diagnostico`} className="recognitionSection05Button recognitionSection05ButtonPrimary">{t.book}</Link><Link href={`/${locale}/contact`} className="recognitionSection05Button">{t.talk}</Link></div></figure></div></section>
</main>}
export function recognitionHref(locale:Locale){return locale==='es'?'/es/reconocimiento':'/en/recognition'}
