import Link from 'next/link'
import type { Locale } from '@/lib/get-locale'
import s from './recognition-page.module.css'

const copy = {
  en: {
    heroEyebrow: 'Vision · Recognition · Workflows', heroTitle: 'Smart Recognition Systems.', heroBody: 'Computer vision systems for wildlife, production quality, agriculture and security that connect detections to real operational workflows.', heroPrimary: 'Book a diagnosis', heroSecondary: 'See use cases',
    useEyebrow: '02 · Core Use Cases', useTitle: 'Recognition across real operations.', useIntro: 'One recognition layer. Multiple operational contexts. Each use case connects visual evidence to a measurable workflow.',
    useCases: [['Wildlife Recognition','Detect cougar, pudú and conservation events in forests, parks and remote areas.'],['Cattle Recognition','Count livestock, register feeding events and monitor herd movement.'],['Production Quality Recognition','Measure size, color, defects and premium quality across products and batches.'],['Security Recognition','Detect people, vehicles, intrusion and perimeter events in critical areas.']],
    valueEyebrow:'03 · Value Chain', valueTitle:'Detection becomes action.', valueBody:'N3uralia transforms raw detections into operational workflows that create records, alerts, and business actions across your organization.', valueNoteTitle:"Events don’t become workflows by themselves.", valueNoteBody:'A detection only creates value when it becomes a record, an alert, or an action.',
    flow:[['Detect','Capture events in real time.'],['Identify / Classify','Understand what happened.'],['Evaluate / Score','Assess risk and prioritize.'],['Register / Record','Create a trusted operational record.'],['Trigger Action','Initiate actions across systems.']], trace:'Trace & Improve', traceBody:'Close the loop with visibility and continuous improvement.',
    platformEyebrow:'04 · Platform', platformTitle:'The system behind recognition.', platformBody:'N3uralia connects capture, vision intelligence, decision logic, operational records and enterprise integrations in one recognition stack.', layers:[['01','Edge Capture','Camera scans the environment.'],['02','Visual Intelligence','Classifies and compares with confidence.'],['03','Logic & Action','Detection becomes an operational alert.'],['04','Records & Insights','Every event recorded. Insights that matter.'],['05','N3uralia Intelligence','One platform. Everything connected.']], workEyebrow:'Start with one use case.', workTitle:'From diagnosis to pilot to scale.', work:[['01','Diagnose','Assess your operation, constraints, and goals.'],['02','Pilot','Deploy a measurable pilot in one site or line.'],['03','Scale','Scale across teams, workflows, and facilities.']], book:'Book a diagnosis', talk:'Talk to us',
  },
  es: {
    heroEyebrow:'Visión · Reconocimiento · Flujos', heroTitle:'Sistemas de reconocimiento inteligente.', heroBody:'Sistemas de visión computacional para fauna, calidad de producción, agricultura y seguridad que conectan detecciones con flujos operacionales reales.', heroPrimary:'Agendar diagnóstico', heroSecondary:'Ver casos de uso', useEyebrow:'02 · Casos de Uso', useTitle:'Reconocimiento en operaciones reales.', useIntro:'Una capa de reconocimiento. Múltiples contextos operacionales. Cada caso conecta evidencia visual con un flujo medible.', useCases:[['Reconocimiento de Fauna','Detecta puma, pudú y eventos de conservación en bosques, parques y zonas remotas.'],['Reconocimiento Ganadero','Cuenta ganado, registra eventos de alimentación y monitorea el movimiento del rebaño.'],['Reconocimiento de Calidad','Mide tamaño, color, defectos y calidad premium en productos y lotes.'],['Reconocimiento de Seguridad','Detecta personas, vehículos, intrusión y eventos perimetrales en áreas críticas.']],
    valueEyebrow:'03 · Cadena de Valor', valueTitle:'La detección se convierte en acción.', valueBody:'N3uralia transforma detecciones en flujos operacionales que crean registros, alertas y acciones de negocio en toda la organización.', valueNoteTitle:'Los eventos no se convierten solos en flujos.', valueNoteBody:'Una detección crea valor cuando se convierte en un registro, una alerta o una acción.', flow:[['Detectar','Captura eventos en tiempo real.'],['Identificar / Clasificar','Comprende qué ocurrió.'],['Evaluar / Puntuar','Evalúa riesgo y prioriza.'],['Registrar','Crea un registro operacional confiable.'],['Activar Acción','Inicia acciones entre sistemas.']], trace:'Trazar y Mejorar', traceBody:'Cierra el ciclo con visibilidad y mejora continua.',
    platformEyebrow:'04 · Plataforma', platformTitle:'El sistema detrás del reconocimiento.', platformBody:'N3uralia conecta captura, inteligencia visual, lógica de decisión, registros operacionales e integraciones empresariales en una sola arquitectura.', layers:[['01','Captura Edge','La cámara escanea el entorno.'],['02','Inteligencia Visual','Clasifica y compara con confianza.'],['03','Lógica y Acción','La detección se convierte en una alerta operacional.'],['04','Registros e Insights','Cada evento queda registrado. Insights que importan.'],['05','Inteligencia N3uralia','Una plataforma. Todo conectado.']], workEyebrow:'Comienza con un caso de uso.', workTitle:'Del diagnóstico al piloto y a escala.', work:[['01','Diagnosticar','Evalúa tu operación, restricciones y objetivos.'],['02','Piloto','Implementa un piloto medible en un sitio o línea.'],['03','Escalar','Escala entre equipos, flujos e instalaciones.']], book:'Agendar diagnóstico', talk:'Hablar con nosotros',
  },
} as const

const useCaseAssets=[['/usecase-cougar-clean.webp','Clean dark image of a Chilean cougar for wildlife recognition.'],['/usecase-cow-clean.webp','Clean dark image of a healthy cow for cattle recognition.'],['/usecase-sea-urchin-clean.webp','Sea urchin specimen inspection for production quality recognition.'],['/usecase-security-clean.webp','Human moving through a secured perimeter at night for security recognition.']] as const

export function RecognitionPage({locale}:{locale:Locale}){const t=copy[locale];return <main className={s.page}>
<section className={`${s.section} ${s.hero}`}><div className={`${s.shell} ${s.heroContent}`}><span className={s.eyebrow}>{t.heroEyebrow}</span><h1>{t.heroTitle}</h1><p className={s.heroBody}>{t.heroBody}</p><div className={s.actions}><Link href={`/${locale}/diagnostico`} className={`${s.button} ${s.buttonPrimary}`}>{t.heroPrimary}</Link><a href="#use-cases" className={s.button}>{t.heroSecondary}</a></div><div className={s.heroSignal} aria-hidden="true"><span className={s.signalMark}/><span>Intelligence built on real data.<br/>Impact delivered in the field.</span></div></div></section>
<section id="use-cases" className={`${s.section} ${s.useCases}`}><div className={s.shell}><div className={s.useCaseLead}><header className={s.sectionHead}><span className={s.eyebrow}>{t.useEyebrow}</span><h2>{t.useTitle}</h2><p>{t.useIntro}</p></header><figure className={`${s.mediaFrame} ${s.useCaseFeature}`}><img src="/usecase-operations-overview.webp" alt="Wildlife monitoring command center detecting a cougar." className={s.visual}/></figure></div><div className={s.cardGrid}>{t.useCases.map((item,i)=><article className={s.useCaseCard} key={item[0]}><div className={s.cardMedia}><img src={useCaseAssets[i][0]} alt={useCaseAssets[i][1]} loading="lazy" className={s.visual}/></div><div className={s.cardBody}><span>0{i+1}</span><h3>{item[0]}</h3><p>{item[1]}</p></div></article>)}</div></div></section>
<section className={`${s.section} ${s.value} valueChainSection`}><div className={s.shell}><div className="valueChainTop"><header><span className={s.eyebrow}>{t.valueEyebrow}</span><h2>{t.valueTitle}</h2><i/><p>{t.valueBody}</p></header><aside><span className="valueDbIcon" aria-hidden="true"/><div><strong>{t.valueNoteTitle}</strong><p>{t.valueNoteBody}</p></div></aside></div><div className="valueFlow"><div className="valueFlowRail"/>{t.flow.map((step,index)=><article className="valueFlowStep" key={step[0]}><span className="valueStepNo">0{index+1}</span><div className="valueIcon" aria-hidden="true"><span/></div><h3>{step[0]}</h3><p>{step[1]}</p>{index<t.flow.length-1&&<span className="valueArrow" aria-hidden="true"/>}</article>)}<div className="valueReturn"><span aria-hidden="true"/><strong>{t.trace}</strong><p>{t.traceBody}</p></div></div><footer className="valueFooter"><span aria-hidden="true"/><b>Intelligence built on real data.<br/>Impact delivered in the field.</b><i/><b>Built for operations. Designed for impact.</b></footer></div></section>
<section id="platform" className={`${s.section} ${s.platform}`}><div className={`${s.shell} ${s.platformGrid}`}>
<div className={s.platformCopy}><span className={s.eyebrow}>{t.platformEyebrow}</span><h2>{t.platformTitle}</h2><p>{t.platformBody}</p><div className={s.layerList}>{t.layers.map(layer=><article className={s.layerItem} key={layer[0]}><span>{layer[0]}</span><div><h3>{layer[1]}</h3><p>{layer[2]}</p></div></article>)}</div></div>
<figure className={`${s.mediaFrame} ${s.platformVisual}`} style={{minHeight:'520px',aspectRatio:'auto',padding:'28px',display:'grid',gridTemplateRows:'auto 1fr auto',gap:'22px',background:'radial-gradient(circle at 50% 28%, rgba(29,148,158,.14), transparent 38%), #02090b'}} aria-label="Recognition workflow visual system">
<div style={{display:'flex',justifyContent:'space-between',gap:'18px',alignItems:'flex-start',borderBottom:'1px solid rgba(128,183,179,.18)',paddingBottom:'18px'}}><div><span style={{display:'block',fontFamily:'var(--font-rajdhani),sans-serif',fontSize:'10px',letterSpacing:'.22em',textTransform:'uppercase',color:'#75aaa7'}}>Recognition Core / Live</span><strong style={{display:'block',marginTop:'8px',fontFamily:'var(--font-rajdhani),sans-serif',fontSize:'22px',fontWeight:400,letterSpacing:'.12em',textTransform:'uppercase',color:'#c4d9d7'}}>Operational intelligence pipeline</strong></div><div style={{textAlign:'right',fontFamily:'var(--font-rajdhani),sans-serif'}}><span style={{display:'block',fontSize:'9px',letterSpacing:'.18em',textTransform:'uppercase',color:'#668f8c'}}>Detection confidence</span><b style={{display:'block',fontSize:'28px',fontWeight:400,letterSpacing:'.06em',color:'#79d4cf'}}>98.7%</b></div></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:'12px',alignContent:'center'}}>{t.layers.map((layer,index)=><article key={layer[0]} style={{position:'relative',minHeight:index===4?'128px':'142px',gridColumn:index===4?'1 / -1':undefined,border:'1px solid rgba(128,183,179,.26)',background:'linear-gradient(180deg,rgba(7,20,22,.88),rgba(2,9,11,.94))',padding:'18px',boxShadow:'inset 0 0 0 1px rgba(31,116,122,.08)'}}><span style={{display:'inline-flex',width:'34px',height:'34px',alignItems:'center',justifyContent:'center',border:'1px solid rgba(121,212,207,.58)',borderRadius:'50%',fontFamily:'var(--font-rajdhani),sans-serif',fontSize:'11px',letterSpacing:'.08em',color:'#79d4cf'}}>{layer[0]}</span><h3 style={{margin:'15px 0 7px',fontSize:'13px',letterSpacing:'.11em',color:'#b8cfcd'}}>{layer[1]}</h3><p style={{margin:0,fontSize:'9px',lineHeight:1.55,maxWidth:'260px'}}>{layer[2]}</p><span aria-hidden="true" style={{position:'absolute',right:'15px',top:'15px',width:'34px',height:'1px',background:'rgba(121,212,207,.38)'}}/></article>)}</div>
<figcaption style={{display:'flex',justifyContent:'space-between',gap:'18px',borderTop:'1px solid rgba(128,183,179,.18)',paddingTop:'16px',fontFamily:'var(--font-rajdhani),sans-serif',fontSize:'9px',letterSpacing:'.16em',textTransform:'uppercase',color:'#668f8c'}}><span>Capture → Understand → Decide → Record → Learn</span><span>N3uralia / 04</span></figcaption>
</figure>
</div></section>
<section className={`${s.section} ${s.work}`}><div className={`${s.shell} ${s.workGrid}`}><div className={s.workCopy}><span className={s.eyebrow}>{t.workEyebrow}</span><h2>{t.workTitle}</h2><div className={s.workSteps}>{t.work.map(step=><article key={step[0]} className={s.workStep}><span>{step[0]}</span><div><h3>{step[1]}</h3><p>{step[2]}</p></div></article>)}</div><div className={s.actions}><Link href={`/${locale}/diagnostico`} className={`${s.button} ${s.buttonPrimary}`}>{t.book}</Link><Link href={`/${locale}/contact`} className={s.button}>{t.talk}</Link></div><address className={s.contact}><a href="mailto:juan@n3uralia.com">juan@n3uralia.com</a><a href="https://wa.me/56993826127">+56 9 9382 6127</a><span>Santiago, Chile · LATAM</span></address></div><figure className={`${s.mediaFrame} ${s.workVisual}`}><img src="/background-demo-solutions.jpg" alt="Operational command center monitoring recognition systems at scale." loading="lazy" className={s.visual}/></figure></div></section>
</main>}
export function recognitionHref(locale:Locale){return locale==='es'?'/es/reconocimiento':'/en/recognition'}
