export const coreSitemapRoutes = [
  ['', 1, 'weekly'],
  ['/soluciones', 0.95, 'weekly'],
  ['/contact', 0.9, 'monthly'],
  ['/diagnostico', 0.9, 'monthly'],
  ['/capabilities', 0.8, 'monthly'],
  ['/como-trabajamos', 0.8, 'monthly'],
  ['/how-we-work', 0.8, 'monthly'],
  ['/case-studies', 0.85, 'weekly'],
  ['/blog', 0.85, 'weekly'],
  ['/faq', 0.75, 'monthly'],
  ['/about', 0.75, 'monthly'],
  ['/nuestro-enfoque', 0.7, 'monthly'],
  ['/como-funcionamos', 0.7, 'monthly'],
  ['/agent-matrix', 0.7, 'monthly'],
  ['/agent-operations', 0.7, 'monthly'],
] as const
