export const coreSitemapRoutes = [
  ['', 1, 'weekly'],
  ['/soluciones', 0.95, 'weekly'],
  ['/diagnostico', 0.95, 'weekly'],
  ['/case-studies', 0.85, 'weekly'],
  ['/blog', 0.8, 'weekly'],
  ['/faq', 0.75, 'monthly'],
  ['/about', 0.75, 'monthly'],
  ['/contact', 0.6, 'monthly'],
  ['/capabilities', 0.6, 'monthly'],
  ['/como-trabajamos', 0.6, 'monthly'],
  ['/how-we-work', 0.6, 'monthly'],
  ['/nuestro-enfoque', 0.55, 'monthly'],
  ['/como-funcionamos', 0.55, 'monthly'],
] as const
