export const solutionSitemapRoutes = [
  ['/agentic-systems', 0.85, 'monthly'],
  ['/ai-infrastructure', 0.85, 'monthly'],
  ['/automatizacion-para-empresas', 0.85, 'monthly'],
  ['/automatizacion-ventas-leads', 0.85, 'monthly'],
  ['/automatizacion-ia-empresas-chile', 0.85, 'monthly'],
  ['/soluciones-agenticas-chile', 0.85, 'monthly'],
  ['/conversational-intelligence', 0.8, 'monthly'],
  ['/integraciones-empresariales', 0.8, 'monthly'],
  ['/operaciones-autonomas', 0.8, 'monthly'],
  ['/para-empresas', 0.8, 'monthly'],
  ['/para-startups', 0.8, 'monthly'],
  ['/para-desarrolladores', 0.8, 'monthly'],
  ['/platform', 0.7, 'monthly'],
  ['/platform/nodes', 0.65, 'monthly'],
  ['/platform/patterns', 0.65, 'monthly'],
  ['/platform/security', 0.65, 'monthly'],
  // Industry pages remain indexable where they provide substantive vertical context.
  ['/agentes-ia-logistica-chile', 0.7, 'monthly'],
  ['/agentes-ia-manufactura-chile', 0.7, 'monthly'],
  ['/agentes-ia-retail-chile', 0.7, 'monthly'],
  ['/agentes-ia-turismo-chile', 0.7, 'monthly'],
] as const
