#!/bin/bash

# N3uralia Google Search Console Submission Script
# This script helps with submitting sitemaps and URLs to Google Search Console

SITE_URL="https://n3uralia.com"
SITEMAP_URL="${SITE_URL}/sitemap.xml"

echo "================================"
echo "N3uralia Google Search Console Setup"
echo "================================"
echo ""
echo "STEP 1: Submit Sitemap to Google"
echo "URL: https://search.google.com/search-console"
echo "Sitemap URL to submit: ${SITEMAP_URL}"
echo ""

echo "STEP 2: Verify All Locale Variants"
echo "Primary URLs for Google Search Console verification:"
echo ""
echo "Spanish (Default):"
echo "  - ${SITE_URL}/es"
echo "  - ${SITE_URL}/es/about"
echo "  - ${SITE_URL}/es/capabilities"
echo "  - ${SITE_URL}/es/case-studies"
echo "  - ${SITE_URL}/es/platform"
echo ""
echo "English:"
echo "  - ${SITE_URL}/en"
echo "  - ${SITE_URL}/en/about"
echo "  - ${SITE_URL}/en/capabilities"
echo "  - ${SITE_URL}/en/case-studies"
echo "  - ${SITE_URL}/en/platform"
echo ""

echo "STEP 3: URL Inspection Tool"
echo "For each major page, use Google's URL Inspection tool:"
echo "  1. Go to: https://search.google.com/search-console"
echo "  2. Select your property"
echo "  3. Paste URL in inspection bar"
echo "  4. Click 'Request indexing' if available"
echo ""

echo "STEP 4: Important Optimizations Already in Place"
echo ""
echo "✓ Robots.txt: public/robots.txt"
echo "  - Allows all crawlers"
echo "  - Specifies crawl-delay: 1"
echo "  - Points to sitemap"
echo ""
echo "✓ Sitemap: /sitemap.xml (dynamic generation)"
echo "  - Includes all pages"
echo "  - Bilingual hreflang tags"
echo "  - Priority scores"
echo "  - Change frequency"
echo ""
echo "✓ Metadata: Centralized via lib/metadata-utils.ts"
echo "  - Canonical URLs"
echo "  - Alternate language links"
echo "  - OpenGraph tags"
echo "  - Twitter cards"
echo ""
echo "✓ Structured Data"
echo "  - Organization schema"
echo "  - WebPage schema"
echo "  - BreadcrumbList schema"
echo "  - Article schema"
echo ""

echo "STEP 5: Request Indexing via API"
echo ""
echo "For manual URL indexing (using Google Search Console API):"
echo "curl -X POST 'https://www.google.com/ping?sitemap=${SITEMAP_URL}'"
echo ""

echo "STEP 6: Monitor Indexing"
echo ""
echo "Regular checks to perform:"
echo "  1. Coverage report - Check for errors/warnings"
echo "  2. Enhancements report - Check mobile usability, AMP, rich snippets"
echo "  3. Performance report - Monitor clicks, impressions, CTR"
echo "  4. Removals - Ensure no accidental exclusions"
echo ""

echo "STEP 7: Bilingual SEO Checklist"
echo ""
echo "✓ hreflang tags: Spanish and English variants linked"
echo "✓ Language metadata: Proper locale in lang attributes"
echo "✓ Content structure: Separate /es and /en paths"
echo "✓ Sitemap: Both locales included with hreflang"
echo "✓ robots.txt: Allow both locales"
echo ""

echo "STEP 8: Ongoing Maintenance"
echo ""
echo "Weekly:"
echo "  - Check Search Console for new crawl errors"
echo "  - Review coverage status"
echo ""
echo "Monthly:"
echo "  - Analyze search performance"
echo "  - Check for new indexing issues"
echo "  - Verify sitemaps are updated"
echo ""
echo "Quarterly:"
echo "  - Full SEO audit"
echo "  - Review keyword rankings"
echo "  - Check competitor benchmarks"
echo ""

echo "================================"
echo "Setup Complete!"
echo "================================"
