16:00:25.515 Running build in Washington, D.C., USA (East) – iad1
16:00:25.515 Build machine configuration: 4 cores, 8 GB
16:00:25.627 Cloning github.com/traviscomber/neuralianew (Branch: v0/travis-2540-4cb059cd, Commit: 3ca3444)
16:00:26.553 Cloning completed: 926.000ms
16:00:26.855 Restored build cache from previous deployment (3z8VuzGRrwFsAGrWDH2d9bKGKB7M)
16:00:27.230 Running "vercel build"
16:00:28.823 Vercel CLI 50.15.1
16:00:29.212 Detected `pnpm-lock.yaml` 9 which may be generated by pnpm@9.x or pnpm@10.x
16:00:29.212 Using pnpm@10.x based on project creation date
16:00:29.213 To use pnpm@9.x, manually opt in using corepack (https://vercel.com/docs/deployments/configure-a-build#corepack)
16:00:29.218 Running "install" command: `npm install`...
16:00:39.084 
16:00:39.084 up to date, audited 849 packages in 10s
16:00:39.084 
16:00:39.084 193 packages are looking for funding
16:00:39.084   run `npm fund` for details
16:00:39.166 
16:00:39.166 6 vulnerabilities (2 moderate, 4 high)
16:00:39.166 
16:00:39.166 To address all issues (including breaking changes), run:
16:00:39.166   npm audit fix --force
16:00:39.166 
16:00:39.166 Run `npm audit` for details.
16:00:39.209 Detected Next.js version: 14.2.35
16:00:39.210 Running "next build"
16:00:39.934   ▲ Next.js 14.2.35
16:00:39.934 
16:00:39.995    Creating an optimized production build ...
16:00:40.231  ⚠ Found lockfile missing swc dependencies, run next locally to automatically patch
16:00:46.249 Failed to compile.
16:00:46.250 
16:00:46.250 ./app/capabilities/page.tsx
16:00:46.250 Error: 
16:00:46.250   [31mx[0m Expression expected
16:00:46.250     ,-[[36;1;4m/vercel/path0/app/capabilities/page.tsx[0m:11:1]
16:00:46.250  [2m11[0m | 
16:00:46.250  [2m12[0m | export default function CapabilitiesPage() {
16:00:46.250  [2m13[0m |   return (
16:00:46.250  [2m14[0m |     <>
16:00:46.250     : [31;1m     ^[0m
16:00:46.250  [2m15[0m |       <main className="min-h-screen bg-background">
16:00:46.250  [2m16[0m |         {/* Hero */}
16:00:46.250  [2m17[0m |         <section className="py-20 border-b border-border px-4">
16:00:46.251     `----
16:00:46.251 
16:00:46.251   [31mx[0m Expected '}', got 'className'
16:00:46.251      ,-[[36;1;4m/vercel/path0/app/capabilities/page.tsx[0m:446:1]
16:00:46.251  [2m446[0m |             </div>
16:00:46.251  [2m447[0m | 
16:00:46.251  [2m448[0m |             {{/* Implementation Considerations */}
16:00:46.251  [2m449[0m |             <div className="mb-12">
16:00:46.251      : [31;1m                 ^^^^^^^^^[0m
16:00:46.251  [2m450[0m |               <h3 className="h3 text-foreground mb-6">Consideraciones de Implementación</h3>
16:00:46.251  [2m451[0m |               <div className="space-y-4">
16:00:46.251  [2m452[0m |                 <div className="pl-6 border-l-2 border-primary/30">
16:00:46.251      `----
16:00:46.251 
16:00:46.251 Caused by:
16:00:46.251     Syntax Error
16:00:46.252 
16:00:46.252 Import trace for requested module:
16:00:46.252 ./app/capabilities/page.tsx
16:00:46.252 
16:00:46.252 
16:00:46.252 > Build failed because of webpack errors
16:00:46.289 Error: Command "next build" exited with 1
